/**
 * Implementacion para pIC32Mz1024efm100.
 */
#include "gpio_config.h"

enum i_pps1{
    pps_RPD2=0,
    pps_RPG8=1,
    pps_RPF4=2,
    pps_RPD10=3,
    pps_RPF1=4,
    pps_RPB9=5,
    pps_RPB10=6,
    pps_RPC14=7,
    pps_RPB5=8,
    pps_RPC1=10,
    pps_RPD14=11,
    pps_RPG1=12,
    pps_RPA14=13,
    pps_RPD6=14,
    pps_RPD3=0,
    pps_RPG7=1,
    pps_RPF5=2,
    pps_RPD11=3,
    pps_RPF0=4,
    pps_RPB1=5,
    pps_RPE5=6,
    pps_RPC13=7,
    pps_RPB3=8,

    pps_RPC4=10,
    pps_RPD15=11,
    pps_RPG0=12,
    pps_RPA15=13,
    pps_RPD7=14,
    pps_RPD9=0,
    pps_RPG6=1,
    pps_RPB8=2,
    pps_RPB15=3,
    pps_RPD4=4,
    pps_RPB0=5,
    pps_RPE3=6,
    pps_RPB7=7,
    pps_RPF12=9,
    pps_RPD12=10,
    pps_RPF8=11,
    pps_RPC3=12,
    pps_RPE9=13,
    pps_RPD1=0,
    pps_RPG9=1,
    pps_RPB14=2,
    pps_RPD0=3,
    pps_RPB6=5,
    pps_RPD5=6,
    pps_RPB2=7,
    pps_RPF3=8,
    pps_RPF13=9,
    pps_No_Connect=10,
    pps_RPF2=11,
    pps_RPC2=12,
    pps_RPE8=13,
};
enum o_pps1{
    pps_No_Connect_o=0,
    pps_U3TX=1,
    pps_U4RTS=2,
    pps_SDO1=5,
    pps_SDO2=6,
    pps_SDO3=7,
    pps_SDO5=9,
    pps_SS6=10,
    pps_OC3=11,
    pps_OC6=12,
    pps_REFCLKO4=13,
    pps_C2OUT=14,
    pps_C1TX=15,
    pps_U1TX=1,
    pps_U2RTS=2,
    pps_U5TX=3,
    pps_U6RTS=4,
    pps_SDO4=8,
    pps_OC4=11,
    pps_OC7=12,
    pps_REFCLKO1=15,
    pps_U3RTS=1,
    pps_U4TX=2,
    pps_U6TX=4,
    pps_SS1=5,
    pps_SS3=7,
    pps_SS4=8,
    pps_SS5=9,
    pps_SDO6=10,
    pps_OC5=11,
    pps_OC8=12,
    pps_C1OUT=14,
    pps_REFCLKO3=15,
    pps_U1RTS=1,
    pps_U2TX=2,
    pps_U5RTS=3,
    pps_SS2=6,
    pps_OC2=11,
    pps_OC1=12,
    pps_OC9=13,
    pps_C2TX=15,
};

/*
 * typedef struct{
    GPIO_PIN_A pin;
    GPIO_DIRECTION direction;
    GPIO_PULLUP pullup;
    GPIO_PULLDOWN pulldown;
    GPIO_SLEW_RATE slew;
    GPIO_OPEN_DRAIN od;
    GPIO_STATE state;
    GPIO_MODE mode;
    GPIO_INTERRUPT interruptState;
}GPIO_ConfigTable;
 */

/**
 * @brief Tabla de configuración de pines del dispositivo.
 * 
 */
static const GPIO_ConfigTable configTable[]={

//    {PORTA_5 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTA_9 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, LOW , {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTA_10, D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, LOW , {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTA_15, D_INPUT , PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, LOW , {MAP_SDI4R,pps_RPA15}, GPIO_INT_DISABLE},
//
//    {PORTB_3 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, LOW , {MAP_RPB3R,pps_SDO3}, GPIO_INT_DISABLE},
//    {PORTB_4 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTB_5 , D_INPUT , PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {MAP_SDI3R,pps_RPB5}, GPIO_INT_DISABLE},
//    {PORTB_6 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, LOW , {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTB_7 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, LOW , {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTB_8 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, LOW , {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTB_9 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, LOW , {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTB_10, D_INPUT , PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},    
//    {PORTB_11, D_INPUT , PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},    
//    {PORTB_12, D_INPUT , PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},    
//    {PORTB_13, D_INPUT , PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},    
//    {PORTB_14, D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},
//    
//    {PORTC_1 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {MAP_RPC1R,pps_U3TX}, GPIO_INT_DISABLE},
//    {PORTC_3 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTC_4 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},
//    
//    {PORTD_0 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTD_2 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTD_4 , D_INPUT , PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {MAP_U2RXR,pps_RPD4}, GPIO_INT_DISABLE},
//    {PORTD_5 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {MAP_RPD5R,pps_U2TX}, GPIO_INT_DISABLE},
//    {PORTD_10, D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTD_11, D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},
//
//    {PORTE_5 , D_INPUT , PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {MAP_U3RXR,pps_RPE5}, GPIO_INT_DISABLE},
//    {PORTE_6 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTE_7 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTE_8 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTE_9 , D_INPUT , PULLUP_ENABLE , PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_ENABLE},
//
//    {PORTF_0 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTF_1 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTF_2 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {MAP_RPF2R,pps_OC1}, GPIO_INT_DISABLE},
//    {PORTF_4 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTF_5 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {MAP_RPF5R,pps_SDO4}, GPIO_INT_DISABLE},
//    {PORTF_8 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, LOW , {0,AF_NONE}, GPIO_INT_DISABLE},
//    
//    {PORTG_0 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {MAP_RPG0R,pps_U1TX}, GPIO_INT_DISABLE},
//    {PORTG_1 , D_INPUT , PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {MAP_U1RXR,pps_RPG1}, GPIO_INT_DISABLE},
//    {PORTG_6 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTG_7 , D_OUTPUT, PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {MAP_RPG7R,pps_SDO2}, GPIO_INT_DISABLE},
//    {PORTG_8 , D_INPUT , PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE},
//    {PORTG_9 , D_INPUT , PULLUP_DISABLE, PULLDOWN_DISABLE, SR_FASTEST, OD_DISABLE, HIGH, {0,AF_NONE}, GPIO_INT_DISABLE}
    
    {PORTA_5 , D_OUTPUT, HIGH, {0,AF_NONE}          },
    {PORTA_9 , D_OUTPUT, LOW , {0,AF_NONE}          },
    {PORTA_10, D_OUTPUT, LOW , {0,AF_NONE}          },
    {PORTA_15, D_INPUT , LOW , {MAP_SDI4R,pps_RPA15}},

    {PORTB_3 , D_OUTPUT, LOW , {MAP_RPB3R,pps_SDO3} },
    {PORTB_4 , D_OUTPUT, HIGH, {0,AF_NONE}          },
    {PORTB_5 , D_INPUT , HIGH, {MAP_SDI3R,pps_RPB5} },
    {PORTB_6 , D_OUTPUT, LOW , {0,AF_NONE}          },
    {PORTB_7 , D_OUTPUT, LOW , {0,AF_NONE}          },
    {PORTB_8 , D_OUTPUT, LOW , {0,AF_NONE}          },
    {PORTB_9 , D_OUTPUT, LOW , {0,AF_NONE}          },
    {PORTB_10, D_INPUT , HIGH, {0,AF_NONE}          },    
    {PORTB_11, D_INPUT , HIGH, {0,AF_NONE}          },    
    {PORTB_12, D_INPUT , HIGH, {0,AF_NONE}          },    
    {PORTB_13, D_INPUT , HIGH, {0,AF_NONE}          },    
    {PORTB_14, D_OUTPUT, HIGH, {0,AF_NONE}          },

    {PORTC_1 , D_OUTPUT, HIGH, {MAP_RPC1R,pps_U3TX} },
    {PORTC_3 , D_OUTPUT, HIGH, {0,AF_NONE}          },
    {PORTC_4 , D_OUTPUT, HIGH, {0,AF_NONE}          },

    {PORTD_0 , D_OUTPUT, HIGH, {0,AF_NONE}          },
    {PORTD_2 , D_OUTPUT, HIGH, {0,AF_NONE}          },
    {PORTD_4 , D_INPUT , HIGH, {MAP_U2RXR,pps_RPD4} },
    {PORTD_5 , D_OUTPUT, HIGH, {MAP_RPD5R,pps_U2TX} },
    {PORTD_10, D_OUTPUT, HIGH, {0,AF_NONE}          },
    {PORTD_11, D_OUTPUT, HIGH, {0,AF_NONE}          },

    {PORTE_5 , D_INPUT , HIGH, {MAP_U3RXR,pps_RPE5} },
    {PORTE_6 , D_OUTPUT, HIGH, {0,AF_NONE}          },
    {PORTE_7 , D_OUTPUT, HIGH, {0,AF_NONE}          },
    {PORTE_8 , D_OUTPUT, HIGH, {0,AF_NONE}          },
    {PORTE_9 , D_INPUT , HIGH, {0,AF_NONE}          },

    {PORTF_0 , D_OUTPUT, HIGH, {0,AF_NONE}          },
    {PORTF_1 , D_OUTPUT, HIGH, {0,AF_NONE}          },
    {PORTF_2 , D_OUTPUT, HIGH, {MAP_RPF2R,pps_OC1}  },
    {PORTF_4 , D_OUTPUT, HIGH, {0,AF_NONE}          },
    {PORTF_5 , D_OUTPUT, HIGH, {MAP_RPF5R,pps_SDO4} },
    {PORTF_8 , D_OUTPUT, LOW , {0,AF_NONE}          },

    {PORTG_0 , D_OUTPUT, HIGH, {MAP_RPG0R,pps_U1TX} },
    {PORTG_1 , D_INPUT , HIGH, {MAP_U1RXR,pps_RPG1} },
    {PORTG_6 , D_OUTPUT, HIGH, {0,AF_NONE}          },
    {PORTG_7 , D_OUTPUT, HIGH, {MAP_RPG7R,pps_SDO2} },
    {PORTG_8 , D_INPUT , HIGH, {0,AF_NONE}          },
    {PORTG_9 , D_INPUT , HIGH, {0,AF_NONE}          }

};
static const GPIO_Config config ={
    .table = configTable,
    .tableSize = sizeof(configTable)/sizeof(GPIO_ConfigTable)
};

const GPIO_Config* GPIO_GetConfig()
{
    return (const GPIO_Config*)&config;
}